name: Monitor de Seguridad QRO

on:
  schedule:
    - cron: '*/15 * * * *'  # Revisa cada .5 minutos
  workflow_dispatch:        # Activa el botón de prueba manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install feedparser requests

      - name: Ejecutar monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
