name: Monitor de Seguridad Multi-Ciudad

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado para evitar el warning

      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado para evitar el warning
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install feedparser requests

      - name: Ejecutar monitor
        env:
          WEBHOOK_MTY: ${{ secrets.WEBHOOK_MTY }}
          WEBHOOK_CDMX: ${{ secrets.WEBHOOK_CDMX }}
          WEBHOOK_GDL: ${{ secrets.WEBHOOK_GDL }}
          RSS_MTY: ${{ secrets.RSS_MTY }}
          RSS_CDMX: ${{ secrets.RSS_CDMX }}
          RSS_GDL: ${{ secrets.RSS_GDL }}
        run: python main.py
