name: Monitor de Seguridad QRO

on:
  schedule:
    - cron: '*/5 * * * *'  # GitHub lo lanzará cada 5 min aprox.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerías
        run: pip install feedparser requests
      - name: Ejecutar monitor
       env:
          # Webhooks de Discord
          WEBHOOK_MTY: ${{ secrets.WEBHOOK_MTY }}
          WEBHOOK_CDMX: ${{ secrets.WEBHOOK_CDMX }}
          WEBHOOK_GDL: ${{ secrets.WEBHOOK_GDL }}
          # Feeds de RSS.app
          RSS_MTY: ${{ secrets.RSS_MTY }}
          RSS_CDMX: ${{ secrets.RSS_CDMX }}
          RSS_GDL: ${{ secrets.RSS_GDL }}
        run: python main.py
